name: RwaveDetect CI Workflow

on:
  push:
    branches: [main, dev]
    paths-ignore: [docs/**]

  pull_request:
    branches: main
    paths-ignore: [docs/**]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker pull lycheeacaca/rwave-dev:latest

      - name: Run build and tests inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace lycheeacaca/rwave-dev:latest /bin/bash -c "
            ./build.sh
            ./test/test_all.sh
          "

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ${{ github.workspace }}/final.info
          fail_ci_if_error: true
